"""Extract the screenshots embedded in the Miro asset-pipeline SVG export.

The SVG at ``documentation/SolarPunk Jam - Asset Pipeline.svg`` is a Miro board
export.  Every screenshot a contributor needs is base64-embedded inside it, which
makes the file 389 KB of unreviewable diff and makes the images unusable from
anywhere else.

This script pulls each one out into ``documentation/pipeline/images/`` under a
semantic name, so ``pipeline.yaml`` can reference them by path and the renderer
can reattach them to the right step.

It is idempotent: re-running verifies the files already on disk by sha256 rather
than rewriting them.  Use ``--check`` in CI to assert the extracted images still
match the SVG they came from.

Stdlib only, like the sibling validators in ``.github/scripts/``.

Driven by `pipeline.py extract images`; see pipeline_cli/commands/extract.py.
"""

from __future__ import annotations

import base64
import binascii
import hashlib
import re
import struct
from pathlib import Path

from .common import IMAGES_DIR, SVG_PATH

# Maps the SVG's own image ids to the names we want on disk.  The SVG ids are
# export-order artifacts (`IMG_0`, `IMG_2`, ...) and carry no meaning, so the
# mapping is pinned here and the extraction fails loudly if the SVG stops
# matching it -- that is the signal that the board was re-exported and this
# mapping needs a human to re-check it.
#
# `IMG_1` is deliberately absent: that slot is a 32x32 sticky-note icon with no
# id attribute, not a screenshot.
IMAGE_NAMES = {
    "IMG_0": "art_substance_painter_output_template",
    "IMG_7": "art_blender_gltf_export",
    "IMG_3": "update_autogenerated_texture_name",
    "IMG_4": "update_drag_into_godot_filesystem",
    "IMG_5": "update_import_sidecar_in_explorer",
    "IMG_6": "update_commit_with_github_desktop",
    "IMG_2": "integration_new_inherited_scene",
}

EXTENSIONS = {"png": ".png", "jpeg": ".jpg"}

# The Miro export writes: href, then width/height in display px, then the id.
IMAGE_RE = re.compile(
    r'<image[^>]*?href="data:image/(?P<mime>png|jpeg);base64,(?P<data>[A-Za-z0-9+/=]+)"'
    r'[^>]*?width="(?P<w>[\d.]+)px"[^>]*?height="(?P<h>[\d.]+)px"'
    r'[^>]*?id="(?P<id>IMG_\d+)"'
)

# Widget group wrapping each image, used to recover the board coordinates so the
# extracted files keep a trail back to where they sat on the original diagram.
WIDGET_RE = re.compile(
    r'<g data-widget-id="(?P<widget>\d+)">(?P<body>.*?)(?=<g data-widget-id="|\Z)',
    re.DOTALL,
)
TRANSLATE_RE = re.compile(r"transform=\"translate\((-?[\d.]+), (-?[\d.]+)\)")


class ExtractionError(Exception):
    """Raised when the SVG no longer matches what this script expects."""


def png_dimensions(data: bytes) -> tuple[int, int]:
    """Read width/height from a PNG's IHDR chunk."""
    if data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
        raise ExtractionError("not a PNG, or IHDR is not the first chunk")
    width, height = struct.unpack(">II", data[16:24])
    return width, height


def jpeg_dimensions(data: bytes) -> tuple[int, int]:
    """Read width/height from a JPEG's first SOF marker."""
    if data[:2] != b"\xff\xd8":
        raise ExtractionError("not a JPEG")
    offset = 2
    while offset < len(data) - 1:
        if data[offset] != 0xFF:
            offset += 1
            continue
        marker = data[offset + 1]
        # SOF0-SOF15, skipping the non-frame markers in that range.
        if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
            height, width = struct.unpack(">HH", data[offset + 5 : offset + 9])
            return width, height
        if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
            offset += 2
            continue
        (segment_length,) = struct.unpack(">H", data[offset + 2 : offset + 4])
        offset += 2 + segment_length
    raise ExtractionError("no SOF marker found in JPEG")


def intrinsic_dimensions(mime: str, data: bytes) -> tuple[int, int]:
    return png_dimensions(data) if mime == "png" else jpeg_dimensions(data)


def board_positions(svg_text: str) -> dict[str, tuple[float, float]]:
    """Map each image id to the (x, y) of the Miro widget that contains it."""
    positions: dict[str, tuple[float, float]] = {}
    for widget in WIDGET_RE.finditer(svg_text):
        body = widget.group("body")
        image_ids = re.findall(r'id="(IMG_\d+)"', body)
        if not image_ids:
            continue
        translate = TRANSLATE_RE.search(body)
        if not translate:
            continue
        x, y = float(translate.group(1)), float(translate.group(2))
        for image_id in image_ids:
            positions[image_id] = (x, y)
    return positions


class ExtractedImage:
    def __init__(self, svg_id: str, name: str, mime: str, data: bytes, position):
        self.svg_id = svg_id
        self.name = name
        self.mime = mime
        self.data = data
        self.position = position
        self.width, self.height = intrinsic_dimensions(mime, data)
        self.sha256 = hashlib.sha256(data).hexdigest()

    @property
    def filename(self) -> str:
        return self.name + EXTENSIONS[self.mime]

    @property
    def path(self) -> Path:
        return IMAGES_DIR / self.filename


def extract(svg_path: Path = SVG_PATH) -> list[ExtractedImage]:
    """Decode every named screenshot out of the SVG."""
    if not svg_path.is_file():
        raise ExtractionError(f"SVG not found: {svg_path}")

    svg_text = svg_path.read_text(encoding="utf-8")
    positions = board_positions(svg_text)

    images: list[ExtractedImage] = []
    seen: set[str] = set()
    for match in IMAGE_RE.finditer(svg_text):
        svg_id = match.group("id")
        seen.add(svg_id)
        name = IMAGE_NAMES.get(svg_id)
        if name is None:
            raise ExtractionError(
                f"{svg_id} is embedded in the SVG but is not in IMAGE_NAMES. "
                "The board was probably re-exported with new content -- open the "
                "image, decide what step it documents, and add it to the mapping."
            )
        try:
            data = base64.b64decode(match.group("data"), validate=True)
        except (binascii.Error, ValueError) as exc:
            raise ExtractionError(f"{svg_id}: base64 payload is corrupt: {exc}") from exc
        images.append(
            ExtractedImage(svg_id, name, match.group("mime"), data, positions.get(svg_id))
        )

    missing = set(IMAGE_NAMES) - seen
    if missing:
        raise ExtractionError(
            f"expected image(s) {sorted(missing)} were not found in the SVG. "
            "Either the board changed or IMAGE_NAMES is stale."
        )
    return images


def emit_yaml(images: list[ExtractedImage]) -> str:
    """Render the `images:` block for pasting into pipeline.yaml."""
    lines = ["images:"]
    for image in sorted(images, key=lambda i: i.name):
        lines.append(f"  - id: {image.name}")
        lines.append(f"    file: images/{image.filename}")
        lines.append(f"    sha256: {image.sha256}")
        lines.append(f"    width: {image.width}")
        lines.append(f"    height: {image.height}")
        lines.append('    alt: "TODO: describe what this screenshot shows"')
        lines.append("    source:")
        lines.append(f"      svg_image_id: {image.svg_id}")
        if image.position:
            lines.append(f"      board_x: {image.position[0]:.0f}")
            lines.append(f"      board_y: {image.position[1]:.0f}")
    return "\n".join(lines)
