#!/usr/bin/env python3
"""Render documentation/pipeline/pipeline.yaml into a readable PIPELINE.md.

The generated page opens with a Mermaid flowchart -- which GitHub renders
natively -- where the loops are visible: forward edges solid, rework edges
dashed and running backwards, repeat edges thick. Then one section per phase
with the steps, their rules, and the screenshots reattached.

Usage:
    python tools/pipeline/render_pipeline.py            # write PIPELINE.md
    python tools/pipeline/render_pipeline.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    print("ERROR: PyYAML is required. pip install pyyaml", file=sys.stderr)
    raise SystemExit(1)

REPO_ROOT = Path(__file__).resolve().parents[2]
DOC_PATH = REPO_ROOT / "documentation" / "pipeline" / "pipeline.yaml"
OUT_PATH = REPO_ROOT / "documentation" / "pipeline" / "PIPELINE.md"

BANNER = (
    "<!-- Generated by tools/pipeline/render_pipeline.py from pipeline.yaml. "
    "Do not edit by hand; edit pipeline.yaml and re-run the renderer. -->"
)

SEVERITY_MARK = {
    "blocking": "**Required**",
    "warning": "**Recommended**",
    "advisory": "*Worth knowing*",
}
AUTOMATABLE_TEXT = {
    "full": "fully automatable",
    "partial": "partly automatable",
    "none": "not automatable (needs a GUI)",
}


def node_id(step_id: str) -> str:
    """Mermaid chokes on dots in node ids."""
    return step_id.replace(".", "__")


def mermaid_label(text: str) -> str:
    """Make a string safe inside a quoted Mermaid label."""
    return text.replace('"', "'").replace("\n", " ").strip()


def cell(text: str) -> str:
    """Make a string safe inside a markdown table cell."""
    return " ".join(str(text).split()).replace("|", "\\|")


class Renderer:
    def __init__(self, doc: dict[str, Any]):
        self.doc = doc
        self.images = {image["id"]: image for image in doc.get("images", [])}
        self.roles = {role["id"]: role for role in doc.get("roles", [])}
        self.tools = {tool["id"]: tool for tool in doc.get("tools", [])}
        self.lines: list[str] = []

    def write(self, text: str = "") -> None:
        self.lines.append(text)

    # -- document ----------------------------------------------------------

    def render(self) -> str:
        self.lines = []
        self.write(BANNER)
        self.write()
        self.write(f"# {self.doc['title']}")
        self.write()
        if self.doc.get("description"):
            self.write(" ".join(self.doc["description"].split()))
            self.write()

        source = self.doc.get("source") or {}
        if source.get("note"):
            self.write("> " + " ".join(source["note"].split()))
            self.write(">")
            if source.get("diagram"):
                self.write(
                    f"> Derived from [`{Path(source['diagram']).name}`]"
                    f"(../../{source['diagram'].replace(' ', '%20')})"
                    f" ({source.get('status', 'unknown')})."
                )
            self.write()

        self.render_roles()

        for pipeline in self.doc.get("pipelines", []):
            self.render_pipeline(pipeline)

        return "\n".join(self.lines).rstrip() + "\n"

    def render_roles(self) -> None:
        self.write("## Who does what")
        self.write()
        self.write("| Role | Responsibility |")
        self.write("| --- | --- |")
        for role in self.doc.get("roles", []):
            self.write(f"| **{cell(role['title'])}** | {cell(role.get('description', ''))} |")
        self.write()

    # -- pipeline ----------------------------------------------------------

    def render_pipeline(self, pipeline: dict) -> None:
        self.write("---")
        self.write()
        suffix = " (stub)" if pipeline.get("status") == "stub" else ""
        self.write(f"# {pipeline['title']}{suffix}")
        self.write()
        if pipeline.get("summary"):
            self.write(" ".join(pipeline["summary"].split()))
            self.write()

        phases = sorted(pipeline.get("phases", []), key=lambda p: p["lane"])
        if pipeline.get("edges"):
            self.render_flowchart(pipeline, phases)
            self.render_loop_table(pipeline)

        self.render_conventions(pipeline)
        self.render_artifact_kinds(pipeline)

        for phase in phases:
            self.render_phase(pipeline, phase)

        self.render_open_questions(pipeline)

    def render_flowchart(self, pipeline: dict, phases: list[dict]) -> None:
        self.write("## The shape of it")
        self.write()
        self.write(
            "Solid arrows move an asset forward. **Dashed** arrows are rework - "
            "work going back to an earlier owner. **Thick** arrows are repeats of "
            "the same work. The dashed and thick arrows are the pipeline; the "
            "solid ones are just the happy path."
        )
        self.write()
        self.write("```mermaid")
        self.write("flowchart LR")

        for phase in phases:
            self.write(f'  subgraph {phase["id"]}["{mermaid_label(phase["title"])}"]')
            self.write("    direction TB")
            for step in phase["steps"]:
                self.write(f'    {node_id(step["id"])}["{mermaid_label(step["title"])}"]')
            self.write("  end")

        self.write()
        for edge in pipeline.get("edges", []):
            source, target = node_id(edge["from"]), node_id(edge["to"])
            label = edge.get("label")
            if edge["kind"] == "forward":
                arrow = f'-->|"{mermaid_label(label)}"|' if label else "-->"
            elif edge["kind"] == "rework":
                arrow = f'-. "{mermaid_label(label or "rework")}" .->'
            else:
                arrow = f'== "{mermaid_label(label or "repeat")}" ==>'
            self.write(f"  {source} {arrow} {target}")

        # linkStyle indices follow declaration order across the whole graph, so
        # they line up with the loop above.
        rework_indices: list[int] = []
        repeat_indices: list[int] = []
        for position, edge in enumerate(pipeline.get("edges", [])):
            if edge["kind"] == "rework":
                rework_indices.append(position)
            elif edge["kind"] == "repeat":
                repeat_indices.append(position)

        self.write()
        if rework_indices:
            self.write(
                f"  linkStyle {','.join(str(i) for i in rework_indices)} "
                "stroke:#c2410c,stroke-width:2px;"
            )
        if repeat_indices:
            self.write(
                f"  linkStyle {','.join(str(i) for i in repeat_indices)} "
                "stroke:#1d4ed8,stroke-width:3px;"
            )
        self.write("```")
        self.write()

    def render_loop_table(self, pipeline: dict) -> None:
        loops = [e for e in pipeline["edges"] if e["kind"] in ("rework", "repeat")]
        if not loops:
            return
        self.write("### When work goes backwards")
        self.write()
        self.write("| | From | Back to | Because |")
        self.write("| --- | --- | --- | --- |")
        for edge in loops:
            kind = "repeat" if edge["kind"] == "repeat" else "rework"
            self.write(
                f"| {kind} | `{edge['from']}` | `{edge['to']}` | "
                f"{cell(edge.get('condition', ''))} |"
            )
        self.write()

    def render_conventions(self, pipeline: dict) -> None:
        conventions = pipeline.get("conventions") or {}
        if not conventions:
            return

        self.write("## Conventions")
        self.write()

        patterns = conventions.get("naming_patterns", [])
        if patterns:
            self.write("### Naming")
            self.write()
            self.write("| What | Pattern | Example | Not this |")
            self.write("| --- | --- | --- | --- |")
            for pattern in patterns:
                title = pattern["id"].replace("_", " ")
                example = pattern["examples"]["valid"][0]
                counter = pattern["examples"]["invalid"][0]
                self.write(
                    f"| {cell(title)} | `{cell(pattern['pattern'])}` | "
                    f"`{cell(example)}` | `{cell(counter)}` |"
                )
            self.write()
            for pattern in patterns:
                if pattern.get("description"):
                    self.write(
                        f"- **{pattern['id'].replace('_', ' ')}** - "
                        + " ".join(pattern["description"].split())
                    )
            self.write()

        directories = conventions.get("directory_layout", [])
        if directories:
            self.write("### Where things live")
            self.write()
            for directory in directories:
                self.write(f"- `{directory['path']}`")
                self.write(f"  - {' '.join(directory['description'].split())}")
                if directory.get("example"):
                    self.write(f"  - e.g. `{directory['example']}`")
            self.write()

        rules = conventions.get("rules", [])
        if rules:
            self.write("### Rules that apply everywhere")
            self.write()
            for rule in rules:
                self.render_rule(rule)
            self.write()

    def render_artifact_kinds(self, pipeline: dict) -> None:
        kinds = pipeline.get("artifact_kinds", [])
        if not kinds:
            return
        self.write("### Files this pipeline produces")
        self.write()
        self.write("| File | Extensions | Generated? | Must ship with |")
        self.write("| --- | --- | --- | --- |")
        for kind in kinds:
            siblings = ", ".join(f"`{s}`" for s in kind.get("required_siblings", [])) or "-"
            generated = "generated" if kind.get("generated") else "authored"
            extensions = ", ".join(f"`{e}`" for e in kind["extensions"])
            self.write(
                f"| **{cell(kind['title'])}** | {extensions} | {generated} | {siblings} |"
            )
        self.write()
        for kind in kinds:
            if kind.get("description"):
                self.write(f"- **{kind['title']}** - " + " ".join(kind["description"].split()))
        self.write()

    # -- phase / step ------------------------------------------------------

    def render_phase(self, pipeline: dict, phase: dict) -> None:
        self.write("---")
        self.write()
        self.write(f"## {phase['lane']}. {phase['title']}")
        self.write()
        owners = ", ".join(
            self.roles.get(role, {}).get("title", role) for role in phase.get("roles", [])
        )
        self.write(f"**Owner:** {owners}")
        self.write()
        if phase.get("summary"):
            self.write(" ".join(phase["summary"].split()))
            self.write()

        loop = phase.get("loop") or {}
        if loop.get("is_iterative"):
            self.write("> **This is a loop.**")
            if loop.get("iterates_on"):
                self.write(f"> One turn covers: {' '.join(loop['iterates_on'].split())}")
            if loop.get("repeat_trigger"):
                self.write(f"> You come back when: {' '.join(loop['repeat_trigger'].split())}")
            if loop.get("exit_criteria"):
                self.write("> You are out when:")
                for criterion in loop["exit_criteria"]:
                    self.write(f"> - {' '.join(criterion.split())}")
            self.write()

        for step in phase["steps"]:
            self.render_step(step)

    def render_step(self, step: dict) -> None:
        self.write(f"### {step['title']}")
        self.write()
        meta = [f"`{step['id']}`"]
        if step.get("tool"):
            meta.append(self.tools.get(step["tool"], {}).get("name", step["tool"]))
        self.write(" &middot; ".join(meta))
        self.write()
        self.write(" ".join(step["summary"].split()))
        self.write()

        if step.get("instructions"):
            for index, instruction in enumerate(step["instructions"], start=1):
                self.write(f"{index}. {' '.join(instruction.split())}")
            self.write()

        for shot in step.get("screenshots", []):
            image = self.images.get(shot["image_id"])
            if image is None:
                continue
            alt = " ".join(image["alt"].split())
            self.write(f"![{alt}]({image['file']})")
            self.write()
            self.write(f"*{' '.join(shot['caption'].split())}*")
            self.write()

        if step.get("rules"):
            for rule in step["rules"]:
                self.render_rule(rule)
            self.write()

        for entry in step.get("faq", []):
            self.write(f"<details><summary>{cell(entry['question'])}</summary>")
            self.write()
            self.write(" ".join(entry["answer"].split()))
            self.write()
            self.write("</details>")
            self.write()

        agent = step.get("agent")
        if agent:
            note = AUTOMATABLE_TEXT.get(agent["automatable"], agent["automatable"])
            detail = ""
            if agent.get("verification"):
                detail = " Done when: " + " ".join(agent["verification"][0].split())
            self.write(f"<sub>For agents: {note}.{detail}</sub>")
            self.write()

    def render_rule(self, rule: dict) -> None:
        mark = SEVERITY_MARK.get(rule["severity"], rule["severity"])
        statement = " ".join(rule["statement"].split())
        self.write(f"- {mark} — {statement}")
        if rule.get("why"):
            self.write(f"  - *Why:* {' '.join(rule['why'].split())}")

    def render_open_questions(self, pipeline: dict) -> None:
        questions = pipeline.get("open_questions", [])
        if not questions:
            return
        self.write("---")
        self.write()
        self.write("## Open questions")
        self.write()
        self.write(
            "Known disagreements between this document, the code, and the issue "
            "templates. Recorded rather than silently resolved."
        )
        self.write()
        for question in questions:
            self.write(f"### {question['question']}")
            self.write()
            if question.get("context"):
                self.write(" ".join(question["context"].split()))
                self.write()
            if question.get("blocks"):
                self.write("Blocks:")
                for blocked in question["blocks"]:
                    self.write(f"- {' '.join(blocked.split())}")
                self.write()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--doc", type=Path, default=DOC_PATH)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the rendered file on disk is out of date; write nothing",
    )
    args = parser.parse_args(argv)

    doc = yaml.safe_load(args.doc.read_text(encoding="utf-8"))
    rendered = Renderer(doc).render()

    if args.check:
        if not args.out.is_file():
            print(f"ERROR: {args.out} does not exist. Run the renderer.", file=sys.stderr)
            return 1
        current = args.out.read_text(encoding="utf-8")
        if current != rendered:
            print(f"ERROR: {args.out.name} is out of date with pipeline.yaml.", file=sys.stderr)
            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=f"{args.out.name} (committed)",
                tofile=f"{args.out.name} (rendered)",
                lineterm="",
                n=2,
            )
            for line in list(diff)[:60]:
                print(line, file=sys.stderr)
            print("\nRun: python tools/pipeline/render_pipeline.py", file=sys.stderr)
            return 1
        print(f"{args.out.name} is up to date.")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.out.relative_to(REPO_ROOT).as_posix()} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
